/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author asus
 */
public class Kulit extends javax.swing.JFrame {

    /**
     * Creates new form Kulit
     */
    public Kulit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jobat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jcegah = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpenyebab = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboPenyakit = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        jPanel2.setLayout(null);

        jLabel4.setText("Cara Mengobati");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 240, 110, 20);

        jLabel5.setText("Penyebab");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 30, 60, 20);

        jLabel6.setText("Cara Mencegah");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 110, 110, 20);

        jobat.setColumns(20);
        jobat.setRows(5);
        jScrollPane3.setViewportView(jobat);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(130, 240, 530, 130);

        jcegah.setColumns(20);
        jcegah.setRows(5);
        jScrollPane2.setViewportView(jcegah);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(130, 130, 530, 100);

        jpenyebab.setColumns(20);
        jpenyebab.setRows(5);
        jScrollPane1.setViewportView(jpenyebab);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(130, 20, 530, 100);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 170, 670, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healtyme/c3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, 10, 150, 140);

        jLabel2.setFont(new java.awt.Font("Soft Marshmallow", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KULIT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 20, 100, 50);

        jComboPenyakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "Jerawat", "Panu", "Kudis" }));
        jComboPenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPenyakitActionPerformed(evt);
            }
        });
        jPanel1.add(jComboPenyakit);
        jComboPenyakit.setBounds(280, 100, 150, 30);

        jLabel3.setFont(new java.awt.Font("Soft Marshmallow", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Jenis Penyakit:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 90, 130, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ba.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 30, 40, 39);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(640, 0, 40, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(702, 595));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboPenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPenyakitActionPerformed
        if (jComboPenyakit.getSelectedItem().equals("Jerawat")){
            jpenyebab.setText("Ada gangguan pada bagian kelenjar kulit. Kelenjar kulit terhubung secara langsung dengan\nbagian pori-pori kulit. Kelenjar minyak yang ada di bagian bawah kulit dapat terkena infeksi\ndari kotoran luar yang masuk lewat pori-pori, sel-sel kulit mati dan bakteri atau virus\nAkhirnya jerawat akan terbentuk pada bagian pori-pori");
            jcegah.setText("• Bersihkan wajah secara teratur pada pagi dan sore hari. Bersihkan sisa riasan wajah\ndan gunakan produk pelembab kulit yang sesuai dengan tipe kulit wajah.\n" +
                           "• Hindari terlalu banyak mengkonsumsi berbagai jenis makanan yang digoreng, makanan\nkemasan dan makanan yang terlalu banyak mengandung zat aditif pada makanan.\n" +
                           "• Minum air putih secara teratur setiap hari juga bisa membantu meningkatkan proses\nmetabolisme dan mencegah jerawat.\n" +
                           "• Buat diri anda merasa nyaman dan hindari stres. Stres dapat memicu produksi hormon\nyang menyebabkan pertumbuhan jerawat.");
            jobat.setText("• Gunakan pasta gigi yang mengandung bahan bahan triclosan dan hidrogen peroksida.\nTerapkan pasta gigi pada jerawat saat malam hari dan bersihkan pada pagi harinya.\n" +
                          "• Gunakan masker yang dibuat dari jus tomat dan madu. Campur pasta tomat dan madu dan\ngunakan seperti memakai masker.\n" +
                          "• Gunakan madu dan perasan jeruk lemon yang bisa membuat jerawat cepat kering.\n" +
                          "• Tempelkan mentimun yang bisa membuat efek dingin untuk jerawat dan mencegah infeksi.");
        } else
            if (jComboPenyakit.getSelectedItem().equals("Panu")){
            jpenyebab.setText("Adanya infeksi jamur yang menyerang pada bagian pigmen kulit. Infeksi panu yang\nterjadi akan menyebabkan bercak putih yang akan terlihat karena berbeda dengan\nbagian kulit yang lain.");
            jcegah.setText("Memelihara kesehatan kulit adalah langkah yang sangat tepat. Mandi secara teratur\ndan selalu menjaga kelembapan alami kulit.");
            jobat.setText("Salep atau krim untuk kulit yang mengandung beberapa bahan seperti klotrimazol,\nbelerang, mikonazol dan selenium sulfida. Selain itu, biasanya panu juga diobati\nsecara tradisional dengan memakai lengkuas atau jahe yang dioleskan pada bagian panu.");
        } else
            if(jComboPenyakit.getSelectedItem().equals("Kudis")){
            jpenyebab.setText("Serangan tungau atau kutu kecil. Jenis kutu kecil yang sering disebut dengan istilah\nsarcoptes scabiei. Infeksi dari kutu kecil bisa masuk ke bagian dalam kulit kemudian\nmenghisap darah dan menyebabkan bercak kemerahan.");
            jcegah.setText("• Bersihkan semua pakaian dan isi kamar orang yang terkena penyakit kudis.\n" +
                           "• Cuci dan rendam semua pakaian, handuk dan selimut dalam air hangat kemudian\njemur dibawah sinar matahari.\n" +
                           "• Buang semua jenis perlengkapan yang tidak terpakai dalam rumah untuk mencegah\ndijadikan sarang bagi kutu.\n" +
                           "• Bersihkan tempat tidur dengan bahan khusus yang bisa membunuh kutu dan jika perlu\njemur dibawah sinar matahari.");
            jobat.setText("• Penderita biasanya dirawat di rumah sakit di dalam kamar yang tenang\nKeributan bisa\nmerangsang serangan batuk.\n" +
                          "• Pengisapan lendir dari tenggorokan.\n" +
                          "• Merendam bagian kulit yang gatal dengan air dingin, memakai pelembab yang\nmengandung calamine. Jika kondisi sudah parah maka bisa memakai obat antibiotik dan\nantihistamin.");
        }
    }//GEN-LAST:event_jComboPenyakitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home satu = new Home();
                satu.show();
                dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kulit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kulit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kulit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kulit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kulit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboPenyakit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jcegah;
    private javax.swing.JTextArea jobat;
    private javax.swing.JTextArea jpenyebab;
    // End of variables declaration//GEN-END:variables
}
