/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author asus
 */
public class Paruu extends javax.swing.JFrame {

    /**
     * Creates new form Paruu
     */
    public Paruu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpenyebab = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jcegah = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jobat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboPenyakit = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ba.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        jPanel2.setLayout(null);

        jLabel4.setText("Cara Mengobati");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 240, 110, 20);

        jLabel5.setText("Penyebab");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 30, 60, 20);

        jLabel6.setText("Cara Mencegah");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 130, 110, 20);

        jpenyebab.setColumns(20);
        jpenyebab.setRows(5);
        jScrollPane1.setViewportView(jpenyebab);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(130, 20, 530, 100);

        jcegah.setColumns(20);
        jcegah.setRows(5);
        jScrollPane2.setViewportView(jcegah);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(130, 130, 530, 100);

        jobat.setColumns(20);
        jobat.setRows(5);
        jScrollPane3.setViewportView(jobat);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(130, 240, 530, 130);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 170, 670, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healtyme/c1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 20, 140, 140);

        jLabel2.setFont(new java.awt.Font("Soft Marshmallow", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PARU-PARU");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 20, 210, 50);

        jComboPenyakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "Asma", "Bronkientasis", "Pertussis", "Influenza", "Difteri" }));
        jComboPenyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPenyakitActionPerformed(evt);
            }
        });
        jPanel1.add(jComboPenyakit);
        jComboPenyakit.setBounds(280, 110, 150, 30);

        jLabel3.setFont(new java.awt.Font("Soft Marshmallow", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Jenis Penyakit:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 110, 130, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 0, 40, 33);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ba.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(640, 30, 40, 39);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(702, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboPenyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPenyakitActionPerformed
        if (jComboPenyakit.getSelectedItem().equals("Asma")){
            jpenyebab.setText("Penyempitan saluran pernafasan");
            jcegah.setText("Serangan asma dapat dicegah jika faktor pemicunya diketahui dan bisa dihindari.\nSerangan yang dipicu oleh olahraga bisa dihindari dengan meminum obat sebelum\nmelakukan olahraga");
            jobat.setText("• Agonis reseptor beta-adrenergik merupakan obat terbaik untuk mengurangi serangan\n asma yang terjadi secara tiba-tiba dan untuk mencegah serangan yang mungkin dipicu\noleh olahraga. \n" +
                          "• Tablet atau suntikan corticosteroid bisa digunakan selama 1-2 minggu untuk mengurangi\nserangan asma yang berat.\n" +
                          "• Corticosteroid per-oral (ditelan) diberikan untuk jangka panjang hanya jika pengobatan\nlainnya tidak dapat mengendalikan gejala asma.");
        } else
            if (jComboPenyakit.getSelectedItem().equals("Bronkientasis")){
            jpenyebab.setText("• Infeksi pernapasan, Campak, Pertusis, Infeksi adenovirus, Infeksi bakteri\n" +
                              "• Penyalahgunaan obat (misalnya heroin), Infeksi HIV, Sindroma Young (azoospermia\nobstruktif), Sindroma Marfan.");
            jcegah.setText("• Imunisasi campak dan pertusis pada masa kanak-kanak membantu menurunkan angka\nkejadian bronkiektasis.\n" +
                           "• Vaksin influenza berkala membantu mencegah kerusakan bronkus oleh virus flu. Vaksin\npneumokok membantu mencegah komplikasi berat dari pneumonnia pneumokok.");
            jobat.setText("• Drainase postural yang dilakukan secara teratur setiap hari, merupakan bagian dari\npengobatan untuk membuang dahak\n" +
                          "• Untuk mengatasi infeksi seringkali diberikan antibiotik, bronkodilator, dan\nekspektoran.");
        } else
            if(jComboPenyakit.getSelectedItem().equals("Pertussis")){
            jpenyebab.setText(" bacterium Bordetella namun tidak jarang diakibatkan oleh B. Parapertussis ");
            jcegah.setText("Imunisasi pada usia 2, 4, 6, dan 18 bulan dan 4-6 tahun. Diharapkan kemugkinan\nterkenanya pertusis akan makin rendah dengan diberikan nya imunisasi, dan gejala\npenyakit pun tidak akan seberat kalau tanpa diberikannya imunisasi");
            jobat.setText("• Penderita biasanya dirawat di rumah sakit di dalam kamar yang tenang\nKeributan bisa merangsang serangan batuk.\n" +
                          "• Pengisapan lendir dari tenggorokan.\n" +
                          "• Oksigen diberikan langsung ke paru-paru melalui selang yang dimasukkan\nke trakea.");
        } else
            if(jComboPenyakit.getSelectedItem().equals("Influenza")){
            jpenyebab.setText("Virus RNA dari famili Orthomyxoviridae (virus influensa). Penyakit ini ditularkan dengan\nmedium udara melalui bersin dari si penderita");
            jcegah.setText("• Minumlah yang banyak karena air berfungsi untuk membersihkan racun\n" +
                           "• Hiruplah udara segar secara teratur terutama ketika dalam cuaca sejuk\n" +
                           "• Cobalah bersantai agar anda dapat mengaktifkan sistem kekebalan tubuh\nkarena dengan bersantai dapat membantu sistem kekebalan tubuh merespon terhadap virus\ninfluensa");
            jobat.setText("• Makanan yang bergizi dan menjahui potensi-potensi yang menyebabkan influenza\n" +
                          "• Kaum lanjut usia atau mereka yang mengidap penyakit kronis dianjurkan diimunisasi");
        } else
            if(jComboPenyakit.getSelectedItem().equals("Difteri")){
            jpenyebab.setText("Disebarkan dari kulit, saluran pernapasan dan sentuhan dengan penderita difteri\nitu sendiri.");
            jcegah.setText("Dapat dicegah melalui vaksinasi. Bayi, anak-anak, remaja, dan orang dewasa yang tidak\nmempunyai cukup pelalian memerlukan suntikan booster setiap 10 tahun.");
            jobat.setText("Antitoksin difteri, yang melemahkan toksin dan antibiotik. Eritromisin dan penisilin\nmembantu menghilangkan kuman dan menghentikan pengeluaran toksin.");
            }
       
    }//GEN-LAST:event_jComboPenyakitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Home satu = new Home();
        satu.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Home satu = new Home();
        satu.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paruu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paruu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paruu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paruu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paruu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboPenyakit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jcegah;
    private javax.swing.JTextArea jobat;
    private javax.swing.JTextArea jpenyebab;
    // End of variables declaration//GEN-END:variables
}
